print("Churi Bidda Moha Bidya jodi na poro dhora")
print("Churi with command line")
print("hello world")
print("finally")
print("kk")
print("ram")
print("something")
print("ask1")
print("twss")
print("alpha")
